/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPenyakit.java
 *
 * Created on May 23, 2010, 12:57:16 AM
 */

package rekammedis;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.validasi;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author dosen
 */
public final class RMCariKeluhan extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps;
    private ResultSet rs;
    private String norawat="";
    private int z=0;
    /** Creates new form DlgPenyakit
     * @param parent
     * @param modal */
    public RMCariKeluhan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,2);
        setSize(656,250);

        Object[] row={"Tanggal","Jam","Keluhan"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbKamar.setModel(tabMode);
        //tbPenyakit.setDefaultRenderer(Object.class, new WarnaTable(panelJudul.getBackground(),tbPenyakit.getBackground()));
        tbKamar.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbKamar.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (z= 0; z < 3; z++) {
            TableColumn column = tbKamar.getColumnModel().getColumn(z);
            if(z==0){
                column.setPreferredWidth(65);
            }else if(z==1){
                column.setPreferredWidth(50);
            }else if(z==2){
                column.setPreferredWidth(750);
            }
        }
        tbKamar.setDefaultRenderer(Object.class, new WarnaTable());
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        tampil();
                    }
                }
            });
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbKamar = new widget.Table();
        panelisi3 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        label10 = new widget.Label();
        LCount = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Riwayat Keluhan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbKamar.setAutoCreateRowSorter(true);
        tbKamar.setName("tbKamar"); // NOI18N
        tbKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKamarMouseClicked(evt);
            }
        });
        tbKamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKamarKeyPressed(evt);
            }
        });
        Scroll.setViewportView(tbKamar);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelisi3.setName("panelisi3"); // NOI18N
        panelisi3.setPreferredSize(new java.awt.Dimension(100, 43));
        panelisi3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 9));

        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi3.add(label9);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(300, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi3.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi3.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setToolTipText("2Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi3.add(BtnAll);

        label10.setText("Record :");
        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(60, 23));
        panelisi3.add(label10);

        LCount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LCount.setText("0");
        LCount.setName("LCount"); // NOI18N
        LCount.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi3.add(LCount);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('4');
        BtnKeluar.setToolTipText("Alt+4");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        panelisi3.add(BtnKeluar);

        internalFrame1.add(panelisi3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_UP){
            tbKamar.requestFocus();
        }
}//GEN-LAST:event_TCariKeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil();
}//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnCari, TCari);
        }
}//GEN-LAST:event_BtnAllKeyPressed

    private void tbKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKamarMouseClicked
        if(tabMode.getRowCount()!=0){
            if(evt.getClickCount()==2){
                dispose();
            }
        }
}//GEN-LAST:event_tbKamarMouseClicked

    private void tbKamarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKamarKeyPressed
        if(tabMode.getRowCount()!=0){
            if(evt.getKeyCode()==KeyEvent.VK_SPACE){
                dispose();
            }else if(evt.getKeyCode()==KeyEvent.VK_SHIFT){
                TCari.setText("");
                TCari.requestFocus();
            }
        }
}//GEN-LAST:event_tbKamarKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        emptTeks();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RMCariKeluhan dialog = new RMCariKeluhan(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Label LCount;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label10;
    private widget.Label label9;
    private widget.panelisi panelisi3;
    private widget.Table tbKamar;
    // End of variables declaration//GEN-END:variables

    public void tampil() {
        Valid.tabelKosong(tabMode);
        try{
            ps=koneksi.prepareStatement(
                    "select pemeriksaan_ralan.tgl_perawatan,pemeriksaan_ralan.jam_rawat,pemeriksaan_ralan.keluhan "+
                    "from pemeriksaan_ralan where pemeriksaan_ralan.no_rawat=? and "+
                    "(pemeriksaan_ralan.tgl_perawatan like ? or pemeriksaan_ralan.keluhan like ?) "+
                    "order by pemeriksaan_ralan.tgl_perawatan,pemeriksaan_ralan.jam_rawat");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                ps.setString(3,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select pemeriksaan_ranap.tgl_perawatan,pemeriksaan_ranap.jam_rawat,pemeriksaan_ranap.keluhan "+
                    "from pemeriksaan_ranap where pemeriksaan_ranap.no_rawat=? and "+
                    "(pemeriksaan_ranap.tgl_perawatan like ? or pemeriksaan_ranap.keluhan like ?) "+
                    "order by pemeriksaan_ranap.tgl_perawatan,pemeriksaan_ranap.jam_rawat");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                ps.setString(3,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan.tanggal, 12) AS jam,penilaian_medis_ralan.keluhan_utama "+
                    "from penilaian_medis_ralan where penilaian_medis_ralan.no_rawat=? and penilaian_medis_ralan.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_anak.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_anak.tanggal, 12) AS jam,penilaian_medis_ralan_anak.keluhan_utama "+
                    "from penilaian_medis_ralan_anak where penilaian_medis_ralan_anak.no_rawat=? and penilaian_medis_ralan_anak.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_anak.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_bedah.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_bedah.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_bedah.keluhan_utama "+
                    "from penilaian_medis_ralan_bedah where penilaian_medis_ralan_bedah.no_rawat=? and penilaian_medis_ralan_bedah.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_bedah.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_bedah_mulut.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_bedah_mulut.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_bedah_mulut.keluhan_utama "+
                    "from penilaian_medis_ralan_bedah_mulut where penilaian_medis_ralan_bedah_mulut.no_rawat=? and penilaian_medis_ralan_bedah_mulut.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_bedah_mulut.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_geriatri.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_geriatri.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_geriatri.keluhan_utama "+
                    "from penilaian_medis_ralan_geriatri where penilaian_medis_ralan_geriatri.no_rawat=? and penilaian_medis_ralan_geriatri.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_geriatri.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_kandungan.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_kandungan.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_kandungan.keluhan_utama "+
                    "from penilaian_medis_ralan_kandungan where penilaian_medis_ralan_kandungan.no_rawat=? and penilaian_medis_ralan_kandungan.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_kandungan.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_mata.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_mata.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_mata.keluhan_utama "+
                            "from penilaian_medis_ralan_mata where penilaian_medis_ralan_mata.no_rawat=? and penilaian_medis_ralan_mata.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_mata.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_neurologi.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_neurologi.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_neurologi.keluhan_utama "+
                            "from penilaian_medis_ralan_neurologi where penilaian_medis_ralan_neurologi.no_rawat=? and penilaian_medis_ralan_neurologi.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_neurologi.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_orthopedi.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_orthopedi.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_orthopedi.keluhan_utama "+
                            "from penilaian_medis_ralan_orthopedi where penilaian_medis_ralan_orthopedi.no_rawat=? and penilaian_medis_ralan_orthopedi.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_orthopedi.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_penyakit_dalam.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_penyakit_dalam.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_penyakit_dalam.keluhan_utama "+
                            "from penilaian_medis_ralan_penyakit_dalam where penilaian_medis_ralan_penyakit_dalam.no_rawat=? and penilaian_medis_ralan_penyakit_dalam.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_penyakit_dalam.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_psikiatrik.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_psikiatrik.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_psikiatrik.keluhan_utama "+
                            "from penilaian_medis_ralan_psikiatrik where penilaian_medis_ralan_psikiatrik.no_rawat=? and penilaian_medis_ralan_psikiatrik.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_psikiatrik.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ralan_tht.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ralan_tht.tanggal, 12) AS jam,"+
                    "penilaian_medis_ralan_tht.keluhan_utama "+
                            "from penilaian_medis_ralan_tht where penilaian_medis_ralan_tht.no_rawat=? and penilaian_medis_ralan_tht.keluhan_utama like ? "+
                    "order by penilaian_medis_ralan_tht.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ranap.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ranap.tanggal, 12) AS jam,"+
                    "penilaian_medis_ranap.keluhan_utama "+
                            "from penilaian_medis_ranap where penilaian_medis_ranap.no_rawat=? and penilaian_medis_ranap.keluhan_utama like ? "+
                    "order by penilaian_medis_ranap.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select SUBSTRING(penilaian_medis_ranap_kandungan.tanggal, 1, 10) AS ttanggal,SUBSTRING(penilaian_medis_ranap_kandungan.tanggal, 12) AS jam,"+
                    "penilaian_medis_ranap_kandungan.keluhan_utama "+
                    "from penilaian_medis_ranap_kandungan where penilaian_medis_ranap_kandungan.no_rawat=? and penilaian_medis_ranap_kandungan.keluhan_utama like ? "+
                    "order by penilaian_medis_ranap_kandungan.tanggal");
            try{
                ps.setString(1,norawat);
                ps.setString(2,"%"+TCari.getText().trim()+"%");
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        
        try{
            ps=koneksi.prepareStatement(
                    "select substring(penilaian_medis_igd.tanggal,1,10) as tgl,substring(penilaian_medis_igd.tanggal,12) as jam,moi.moi "+
                    "from penilaian_medis_igd left join moi on moi.no_rawat=penilaian_medis_igd.no_rawat where "+
                    "penilaian_medis_igd.no_rawat=?");
            try{
                ps.setString(1,norawat);
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new String[] {
                        rs.getString(1),rs.getString(2),rs.getString(3)
                    });
                }
            }catch(Exception ex){
                System.out.println(ex);
            }finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        LCount.setText(""+tabMode.getRowCount());
    }

    public void emptTeks() {   
        TCari.requestFocus();
    }
    
    public void setNoRawat(String norawat){
        this.norawat=norawat;
    }

    public JTable getTable(){
        return tbKamar;
    }
    
}
