package laporan;
import fungsi.koneksiDB;
import fungsi.validasi;
import fungsi.akses;
import fungsi.sekuel;
import grafikanalisa.grafikepid;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgLaporanRM extends javax.swing.JDialog {
    private final validasi Valid=new validasi();
    private final Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private PreparedStatement ps,ps2,ps3,ps4,ps5,ps6,ps7,ps8,ps9;
    private String l,p;
    private int hitung;
    private ResultSet rs,rs2,rs3,rs4,rs5,rs6;
    private StringBuilder htmlContent;
    private int u15s59l=0,u15s59p=0,u60l=0,u60p=0,u30s55=0,gds=0,chol=0,ua=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgLaporanRM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(false);
        LoadHTML.setEditorKit(kit);
        LoadHTML1.setEditable(false);
        LoadHTML1.setEditorKit(kit);
        LoadHTML2.setEditable(false);
        LoadHTML2.setEditorKit(kit);
        LoadHTML3.setEditable(false);
        LoadHTML3.setEditorKit(kit);
        LoadHTML4.setEditable(false);
        LoadHTML4.setEditorKit(kit);
        LoadHTML5.setEditable(false);
        LoadHTML5.setEditorKit(kit);
        LoadHTML6.setEditable(false);
        LoadHTML6.setEditorKit(kit);
        LoadHTML7.setEditable(false);
        LoadHTML7.setEditorKit(kit);
        LoadHTML8.setEditable(false);
        LoadHTML8.setEditorKit(kit);
        LoadHTML9.setEditable(false);
        LoadHTML9.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML1.setDocument(doc);
        LoadHTML2.setDocument(doc);
        LoadHTML3.setDocument(doc);
        LoadHTML4.setDocument(doc);
        LoadHTML5.setDocument(doc);
        LoadHTML6.setDocument(doc);
        LoadHTML7.setDocument(doc);
        LoadHTML8.setDocument(doc);
        LoadHTML9.setDocument(doc);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    private int i=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        label9 = new widget.Label();
        BtnPrint4 = new widget.Button();
        BtnKeluar = new widget.Button();
        TabRawat = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();
        Scroll2 = new widget.ScrollPane();
        LoadHTML2 = new widget.editorpane();
        Scroll8 = new widget.ScrollPane();
        LoadHTML8 = new widget.editorpane();
        Scroll3 = new widget.ScrollPane();
        LoadHTML3 = new widget.editorpane();
        Scroll4 = new widget.ScrollPane();
        LoadHTML4 = new widget.editorpane();
        Scroll5 = new widget.ScrollPane();
        LoadHTML5 = new widget.editorpane();
        Scroll6 = new widget.ScrollPane();
        LoadHTML6 = new widget.editorpane();
        Scroll7 = new widget.ScrollPane();
        LoadHTML7 = new widget.editorpane();
        Scroll9 = new widget.ScrollPane();
        LoadHTML9 = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Laporan RM ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnPrint4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Bar Chart (copy).png"))); // NOI18N
        BtnPrint4.setMnemonic('G');
        BtnPrint4.setText("Plot");
        BtnPrint4.setToolTipText("Alt+G");
        BtnPrint4.setName("BtnPrint4"); // NOI18N
        BtnPrint4.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrint4ActionPerformed(evt);
            }
        });
        BtnPrint4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrint4KeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint4);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        TabRawat.setBackground(new java.awt.Color(255, 255, 253));
        TabRawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRawatMouseClicked(evt);
            }
        });

        Scroll.setBorder(null);
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        TabRawat.addTab("Epidemiologi", Scroll);

        Scroll1.setBorder(null);
        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        TabRawat.addTab("Jumlah Kunjungan", Scroll1);

        Scroll2.setBorder(null);
        Scroll2.setName("Scroll2"); // NOI18N
        Scroll2.setOpaque(true);

        LoadHTML2.setBorder(null);
        LoadHTML2.setName("LoadHTML2"); // NOI18N
        Scroll2.setViewportView(LoadHTML2);

        TabRawat.addTab("P. Hipertensi Ralan", Scroll2);

        Scroll8.setBorder(null);
        Scroll8.setName("Scroll8"); // NOI18N
        Scroll8.setOpaque(true);

        LoadHTML8.setBorder(null);
        LoadHTML8.setName("LoadHTML8"); // NOI18N
        Scroll8.setViewportView(LoadHTML8);

        TabRawat.addTab("P. Hipertensi Ranap", Scroll8);

        Scroll3.setBorder(null);
        Scroll3.setName("Scroll3"); // NOI18N
        Scroll3.setOpaque(true);

        LoadHTML3.setBorder(null);
        LoadHTML3.setName("LoadHTML3"); // NOI18N
        Scroll3.setViewportView(LoadHTML3);

        TabRawat.addTab("P. Diabetes", Scroll3);

        Scroll4.setBorder(null);
        Scroll4.setName("Scroll4"); // NOI18N
        Scroll4.setOpaque(true);

        LoadHTML4.setBorder(null);
        LoadHTML4.setName("LoadHTML4"); // NOI18N
        Scroll4.setViewportView(LoadHTML4);

        TabRawat.addTab("P. Tidak Menular", Scroll4);

        Scroll5.setBorder(null);
        Scroll5.setName("Scroll5"); // NOI18N
        Scroll5.setOpaque(true);

        LoadHTML5.setBorder(null);
        LoadHTML5.setName("LoadHTML5"); // NOI18N
        Scroll5.setViewportView(LoadHTML5);

        TabRawat.addTab("P. Menular", Scroll5);

        Scroll6.setBorder(null);
        Scroll6.setName("Scroll6"); // NOI18N
        Scroll6.setOpaque(true);

        LoadHTML6.setBorder(null);
        LoadHTML6.setName("LoadHTML6"); // NOI18N
        Scroll6.setViewportView(LoadHTML6);

        TabRawat.addTab("P. Kesga", Scroll6);

        Scroll7.setBorder(null);
        Scroll7.setName("Scroll7"); // NOI18N
        Scroll7.setOpaque(true);

        LoadHTML7.setBorder(null);
        LoadHTML7.setName("LoadHTML7"); // NOI18N
        Scroll7.setViewportView(LoadHTML7);

        TabRawat.addTab("ISPA/Pneumonia", Scroll7);

        Scroll9.setBorder(null);
        Scroll9.setName("Scroll9"); // NOI18N
        Scroll9.setOpaque(true);

        LoadHTML9.setBorder(null);
        LoadHTML9.setName("LoadHTML9"); // NOI18N
        Scroll9.setViewportView(LoadHTML9);

        TabRawat.addTab("Dengue", Scroll9);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint4,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }else if(TabRawat.getSelectedIndex()==2){
            prosesCari3();
        }else if(TabRawat.getSelectedIndex()==3){
            prosesCari9();
        }else if(TabRawat.getSelectedIndex()==4){
            prosesCari4();
        }else if(TabRawat.getSelectedIndex()==5){
            prosesCari5();
        }else if(TabRawat.getSelectedIndex()==6){
            prosesCari6();
        }else if(TabRawat.getSelectedIndex()==7){
            prosesCari7();
        }else if(TabRawat.getSelectedIndex()==8){
            prosesCari8();
        }else if(TabRawat.getSelectedIndex()==9){
            prosesCari10();
        }
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint4);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRawatMouseClicked
        if(TabRawat.getSelectedIndex()==0){
            prosesCari();
        }else if(TabRawat.getSelectedIndex()==1){
            prosesCari2();
        }else if(TabRawat.getSelectedIndex()==2){
            prosesCari3();
        }else if(TabRawat.getSelectedIndex()==3){
            prosesCari9();
        }else if(TabRawat.getSelectedIndex()==4){
            prosesCari4();
        }else if(TabRawat.getSelectedIndex()==5){
            prosesCari5();
        }else if(TabRawat.getSelectedIndex()==6){
            prosesCari6();
        }else if(TabRawat.getSelectedIndex()==7){
            prosesCari7();
        }else if(TabRawat.getSelectedIndex()==8){
            prosesCari8();
        }else if(TabRawat.getSelectedIndex()==9){
            prosesCari10();
        }
    }//GEN-LAST:event_TabRawatMouseClicked

    private void BtnPrint4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrint4ActionPerformed
        if(TabRawat.getSelectedIndex()==0){
            grafikepid kas=new grafikepid("Grafik Epidemiologi "+Valid.SetTgl(Tgl1.getSelectedItem()+"")+" S.D. "+Valid.SetTgl(Tgl2.getSelectedItem()+""),"where tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' ");
            kas.setSize(TabRawat.getWidth(),TabRawat.getHeight());
            kas.setModal(true);
            kas.setAlwaysOnTop(true);
            kas.setLocationRelativeTo(TabRawat);
            kas.setVisible(true);
        }
    }//GEN-LAST:event_BtnPrint4ActionPerformed

    private void BtnPrint4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrint4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrint4KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgLaporanRM dialog = new DlgLaporanRM(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint4;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.editorpane LoadHTML1;
    private widget.editorpane LoadHTML2;
    private widget.editorpane LoadHTML3;
    private widget.editorpane LoadHTML4;
    private widget.editorpane LoadHTML5;
    private widget.editorpane LoadHTML6;
    private widget.editorpane LoadHTML7;
    private widget.editorpane LoadHTML8;
    private widget.editorpane LoadHTML9;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private widget.ScrollPane Scroll2;
    private widget.ScrollPane Scroll3;
    private widget.ScrollPane Scroll4;
    private widget.ScrollPane Scroll5;
    private widget.ScrollPane Scroll6;
    private widget.ScrollPane Scroll7;
    private widget.ScrollPane Scroll8;
    private widget.ScrollPane Scroll9;
    private javax.swing.JTabbedPane TabRawat;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='19%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Umur</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>JK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal Onset</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal Dilaporkan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Desa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Sumber Laporan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Kd Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Pemeriksaan Lab</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Jenis Pemeriksaan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Hasil</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT \n" +
                    "    rp.no_rawat,\n" +
                    "    rp.no_rkm_medis,\n" +
                    "    p.nm_pasien,\n" +
                    "    CONCAT(rp.umurdaftar, ' ', rp.sttsumur) AS umur,\n" +
                    "    IF(p.jk='L', 'Laki-Laki', 'Perempuan') AS jk,\n" +
                    "    p.alamat AS desa,\n" +
                    "    p.no_ktp,\n" +
                    "    CONCAT(kl.nm_kel, ', ', kc.nm_kec, ', ', kb.nm_kab) AS alamat,\n" +
                    "    p.no_tlp,\n" +
                    "    rp.p_jawab,\n" +
                    "    DATE_FORMAT(rp.tgl_registrasi, '%d %M %Y') AS tanggal,\n" +
                    "    dp.kd_penyakit,\n" +
                    "    pn.nm_penyakit,\n" +
                    "    IFNULL(ki.stts_pulang, 'Ralan') AS status_pulang,\n" +
                    "    IFNULL(GROUP_CONCAT(DISTINCT jpl.nm_perawatan SEPARATOR ', '), '-') AS lab\n" +
                    "FROM reg_periksa rp\n" +
                    "INNER JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis\n" +
                    "INNER JOIN diagnosa_pasien dp ON dp.no_rawat = rp.no_rawat\n" +
                    "INNER JOIN penyakit pn ON pn.kd_penyakit = dp.kd_penyakit\n" +
                    "INNER JOIN kelurahan kl ON kl.kd_kel = p.kd_kel\n" +
                    "INNER JOIN kecamatan kc ON kc.kd_kec = p.kd_kec\n" +
                    "INNER JOIN kabupaten kb ON kb.kd_kab = p.kd_kab\n" +
                    "LEFT JOIN kamar_inap ki ON ki.no_rawat = rp.no_rawat \n" +
                    "    AND ki.stts_pulang <> 'Pindah Kamar'\n" +
                    "LEFT JOIN periksa_lab pl ON pl.no_rawat = rp.no_rawat\n" +
                    "LEFT JOIN jns_perawatan_lab jpl ON jpl.kd_jenis_prw = pl.kd_jenis_prw\n" +
                    "WHERE rp.tgl_registrasi BETWEEN ? AND ? and (\n" +
                    "    dp.kd_penyakit IN (\n" +
                    "        'B54', 'A90', 'J18.9', 'J69.0', 'J18.0', 'A06.0', 'A01.0', \n" +
                    "        'B15', 'A92.0', 'B05.9', 'B36.9', 'A37.9', 'A82.9', 'A27.9', \n" +
                    "        'A09', 'A33', 'A35', 'J11', 'B34.2', 'A91', 'A09.9'\n" +
                    "    )\n" +
                    "    OR \n" +
                    "    dp.kd_penyakit REGEXP '^(J0[0-6,9]|J1[0-8]|J2[0-2])'\n" +
                    "  )\n" +
                    "  AND rp.status_lanjut = 'Ranap'\n" +
                    "GROUP BY rp.no_rawat, dp.kd_penyakit\n" +
                    "ORDER BY rp.tgl_registrasi ASC, rp.no_rkm_medis ASC;");
            ps2=koneksi.prepareStatement("SELECT \n" +
                    "    penyakit.nm_penyakit, \n" +
                    "    kelurahan.nm_kel, \n" +
                    "    COUNT(kelurahan.kd_kel) AS jml\n" +
                    "FROM reg_periksa \n" +
                    "INNER JOIN pasien ON pasien.no_rkm_medis = reg_periksa.no_rkm_medis\n" +
                    "INNER JOIN diagnosa_pasien ON diagnosa_pasien.no_rawat = reg_periksa.no_rawat \n" +
                    "INNER JOIN penyakit ON penyakit.kd_penyakit = diagnosa_pasien.kd_penyakit \n" +
                    "INNER JOIN kelurahan ON kelurahan.kd_kel = pasien.kd_kel \n" +
                    "INNER JOIN kecamatan ON kecamatan.kd_kec = pasien.kd_kec \n" +
                    "INNER JOIN kabupaten ON kabupaten.kd_kab = pasien.kd_kab \n" +
                    "WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? \n" +
                    "AND (\n" +
                    "    diagnosa_pasien.kd_penyakit IN (\n" +
                    "        'B54', 'A90', 'J18.9', 'J69.0', 'J18.0', 'A06.0', 'A01.0', \n" +
                    "        'B15', 'A92.0', 'B05.9', 'B36.9', 'A37.9', 'A82.9', 'A27.9', \n" +
                    "        'A09', 'A33', 'A35', 'J11', 'B34.2', 'A91', 'A09.9'\n" +
                    "    )\n" +
                    "    OR diagnosa_pasien.kd_penyakit REGEXP '^(J0[0-6,9]|J1[0-8]|J2[0-2])'\n" +
                    ")\n" +
                    "AND reg_periksa.status_lanjut = 'Ranap' \n" +
                    "AND kelurahan.nm_kel <> '-'\n" +
                    "GROUP BY diagnosa_pasien.kd_penyakit, kelurahan.kd_kel \n" +
                    "ORDER BY kelurahan.nm_kel ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                rs2=ps2.executeQuery();
                i=1;
                while(rs.next()){
                    if(rs.getString("lab").equals("-")){
                        htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'>"+i+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
    //                          "<td valign='middle' align='center'>"+l+"</td>"+
    //                          "<td valign='middle' align='center'>"+p+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("umur")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("jk")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("desa")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                                "<td valign='middle' align='center'>Rumah Sakit</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                                "<td valign='middle' align='center'>Terverivikasi</td>"+
                                "<td valign='middle' align='center'>Tidak</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("lab")+"</td>"+
                                "<td valign='middle' align='center'>Negatif</td>"+
                            "</tr>"
                        );
                        i++;
                    }else{
                        htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'>"+i+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
    //                          "<td valign='middle' align='center'>"+l+"</td>"+
    //                          "<td valign='middle' align='center'>"+p+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("umur")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("jk")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("desa")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                                "<td valign='middle' align='center'>Rumah Sakit</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                                "<td valign='middle' align='center'>Terverivikasi</td>"+
                                "<td valign='middle' align='center'>Ya</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("lab")+"</td>"+
                                "<td valign='middle' align='center'>Positif</td>"+
                            "</tr>"
                        );
                        i++;
                    }
                }
                htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                            "</tr>"
                        );
                htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'>Diagnosa:</td>"+
                                "<td valign='middle' align='left'>Desa:</td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                            "</tr>"
                        );
                while(rs2.next()){
                    htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'>"+rs2.getString("nm_penyakit")+"</td>"+
                                "<td valign='middle' align='left'>"+rs2.getString("nm_kel")+"</td>"+
                                "<td valign='middle' align='center'>"+rs2.getString("jml")+"</td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='left'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                                "<td valign='middle' align='center'></td>"+
                            "</tr>"
                        );
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
        
    }
    
    private void prosesCari2() {
       this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%' rowspan='2'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%' rowspan='2'>Desa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Jumlah Kunjungan Usia 15-59 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' colspan='2'>Jumlah Kunjungan Usia 60 Th Keatas</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%' rowspan='2'>Jumlah Kunjungan WUS Usia 30-55 Th</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='15%' colspan='3'>Jumlah Pemeriksaan Lab Sederhana</td>"+
                "</tr>"+
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>GDS</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>CHOL</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center'>UA</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("select kelurahan.nm_kel from kelurahan inner join pasien on pasien.kd_kel=kelurahan.kd_kel inner join reg_periksa on reg_periksa.no_rkm_medis=pasien.no_rkm_medis "
                    + "where reg_periksa.tgl_registrasi between ? and ? and"+
                    " (kelurahan.nm_kel='JAGAPATI' or kelurahan.nm_kel='ANGANTAKA' or kelurahan.nm_kel='SEDANG' or kelurahan.nm_kel='MEKAR BHUANA' or kelurahan.nm_kel='MAMBAL')"+
                    " group by kelurahan.nm_kel");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    u15s59l=0;u15s59p=0;u60l=0;u60p=0;u30s55=0;gds=0;chol=0;ua=0;
                    ps2=koneksi.prepareStatement(
                            "select kelurahan.nm_kel,reg_periksa.umurdaftar,reg_periksa.sttsumur,pasien.jk from reg_periksa inner join pasien "+
                            "on reg_periksa.no_rkm_medis=pasien.no_rkm_medis inner join kelurahan on kelurahan.kd_kel=pasien.kd_kel where reg_periksa.tgl_registrasi between ? and ? and kelurahan.nm_kel=?");
                    try {
                        ps2.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps2.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps2.setString(3,rs.getString("nm_kel"));
                        rs2=ps2.executeQuery();
                        while(rs2.next()){
                            if(rs2.getString("sttsumur").equals("Th")){
                                if((rs2.getInt("umurdaftar")>=15)&&(rs2.getInt("umurdaftar")<=59)){
                                    if(rs2.getString("jk").equals("L")){
                                        u15s59l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        u15s59p++;
                                    }
                                }else if(rs2.getInt("umurdaftar")>=60){
                                    if(rs2.getString("jk").equals("L")){
                                        u60l++;
                                    }else if(rs2.getString("jk").equals("P")){
                                        u60p++;
                                    }
                                }if((rs2.getInt("umurdaftar")>=30)&&(rs2.getInt("umurdaftar")<=55)){
                                    if(rs2.getString("jk").equals("P")){
                                        u30s55++;
                                    }
                                }
                            }
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgLaporanRM.prosesCari() 1 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    
                    ps3=koneksi.prepareStatement(
                            "select kelurahan.nm_kel,count(detail_periksa_lab.no_rawat) from detail_periksa_lab inner join reg_periksa "+
                            "on reg_periksa.no_rawat=detail_periksa_lab.no_rawat inner join pasien on pasien.no_rkm_medis=reg_periksa.no_rkm_medis "+
                            "inner join kelurahan on kelurahan.kd_kel=pasien.kd_kel "+
                            "where detail_periksa_lab.id_template='17336' and reg_periksa.tgl_registrasi between ? and ? and kelurahan.nm_kel=?");
                    try {
                        ps3.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps3.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps3.setString(3,rs.getString("nm_kel"));
                        rs2=ps3.executeQuery();
                        while(rs2.next()){
                            gds=rs2.getInt(2);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgLaporanRM.prosesCari() 2 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(ps2!=null){
                            ps2.close();
                        }
                    }
                    ps4=koneksi.prepareStatement(
                            "select kelurahan.nm_kel,count(periksa_lab.no_rawat) from periksa_lab inner join reg_periksa "+
                            "on reg_periksa.no_rawat=periksa_lab.no_rawat inner join pasien on pasien.no_rkm_medis=reg_periksa.no_rkm_medis "+
                            "inner join kelurahan on kelurahan.kd_kel=pasien.kd_kel inner join jns_perawatan_lab on jns_perawatan_lab.kd_jenis_prw=periksa_lab.kd_jenis_prw "+
                            "where jns_perawatan_lab.nm_perawatan like \"%Total cholest%\" and reg_periksa.tgl_registrasi between ? and ? and kelurahan.nm_kel=?");
                    try {
                        ps4.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps4.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps4.setString(3,rs.getString("nm_kel"));
                        rs2=ps4.executeQuery();
                        while(rs2.next()){
                            chol=rs2.getInt(2);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(rs2!=null){
                            rs2.close();
                        }
                    }
                    ps5=koneksi.prepareStatement(
                            "select kelurahan.nm_kel,count(periksa_lab.no_rawat) from periksa_lab inner join reg_periksa "+
                            "on reg_periksa.no_rawat=periksa_lab.no_rawat inner join pasien on pasien.no_rkm_medis=reg_periksa.no_rkm_medis "+
                            "inner join kelurahan on kelurahan.kd_kel=pasien.kd_kel inner join jns_perawatan_lab on jns_perawatan_lab.kd_jenis_prw=periksa_lab.kd_jenis_prw "+
                            "where jns_perawatan_lab.nm_perawatan like \"%uric%\" and reg_periksa.tgl_registrasi between ? and ? and kelurahan.nm_kel=?");
                    try{
                        ps5.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                        ps5.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                        ps5.setString(3,rs.getString("nm_kel"));
                        rs2=ps5.executeQuery();
                        while(rs2.next()){
                            ua=rs2.getInt(2);
                        }
                    } catch (Exception e) {
                        System.out.println("laporan.DlgLaporanRM.prosesCari() 4 : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                        if(rs2!=null){
                            rs2.close();
                        }
                    }
                    
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_kel")+"</td>"+
                            "<td valign='middle' align='center'>"+u15s59l+"</td>"+
                            "<td valign='middle' align='center'>"+u15s59p+"</td>"+
                            "<td valign='middle' align='center'>"+u60l+"</td>"+
                            "<td valign='middle' align='center'>"+u60p+"</td>"+
                            "<td valign='middle' align='center'>"+u30s55+"</td>"+
                            "<td valign='middle' align='center'>"+gds+"</td>"+
                            "<td valign='middle' align='center'>"+chol+"</td>"+
                            "<td valign='middle' align='center'>"+ua+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML1.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 6 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());        
    }
    
    private void prosesCari3() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT diagnosa_pasien.no_rawat,DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,"
                    + "pasien.nm_pasien,concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') "
                    + "FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,pasien.no_ktp,"
                    + "concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,reg_periksa.status_poli,"
                    + "pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? "
                    + "AND (diagnosa_pasien.kd_penyakit='I10' OR diagnosa_pasien.kd_penyakit='I15.9' OR diagnosa_pasien.kd_penyakit='I15.1' OR "
                    + "diagnosa_pasien.kd_penyakit='I27.2' OR diagnosa_pasien.kd_penyakit='O10.0' OR diagnosa_pasien.kd_penyakit='O10.4' OR "
                    + "diagnosa_pasien.kd_penyakit='O10.9' OR diagnosa_pasien.kd_penyakit='O15.2' OR diagnosa_pasien.kd_penyakit='O15.8' OR "
                    + "diagnosa_pasien.kd_penyakit='I27.0') "
                    + "GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML2.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari4() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT diagnosa_pasien.no_rawat,DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,"
                    + "pasien.nm_pasien,concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') "
                    + "FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,pasien.no_ktp,"
                    + "concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,reg_periksa.status_poli,"
                    + "pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? AND penyakit.nm_penyakit like \"%diabetes%\" "
                    + "GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                     l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML3.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari5() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,pasien.nm_pasien,"
                    + "concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') "
                    + "FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,"
                    + "pasien.no_ktp,concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,reg_periksa.status_poli,"
                    + "pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? AND "
                    + "(diagnosa_pasien.kd_penyakit='J44.9' OR diagnosa_pasien.kd_penyakit='J46' OR diagnosa_pasien.kd_penyakit='Z82.5' OR "
                    + "diagnosa_pasien.kd_penyakit='J45.9' OR diagnosa_pasien.kd_penyakit='J45.8' OR diagnosa_pasien.kd_penyakit='J45.0' OR "
                    + "diagnosa_pasien.kd_penyakit='J45.1' OR diagnosa_pasien.kd_penyakit='F06.6' OR diagnosa_pasien.kd_penyakit LIKE \"%I63.%\" OR "
                    + "reg_periksa.kd_poli='U0005' OR reg_periksa.kd_poli='U0017' OR reg_periksa.kd_poli='U0015' OR reg_periksa.kd_poli='U0016') "
                    + "GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                     l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML4.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari6() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,"
                    + "pasien.nm_pasien,concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,"
                    + "(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') FROM diagnosa_pasien "
                    + "INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,"
                    + "pasien.no_ktp,concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,"
                    + "reg_periksa.status_poli,pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? "
                    + "AND (diagnosa_pasien.kd_penyakit='M90.0' OR diagnosa_pasien.kd_penyakit='A15.2' OR diagnosa_pasien.kd_penyakit='A15.3' "
                    + "OR diagnosa_pasien.kd_penyakit='A19.9' OR diagnosa_pasien.kd_penyakit='A19.0' OR diagnosa_pasien.kd_penyakit='A19.1' "
                    + "OR diagnosa_pasien.kd_penyakit='A19.2' OR diagnosa_pasien.kd_penyakit='A19.8' OR diagnosa_pasien.kd_penyakit='A18.8' "
                    + "OR diagnosa_pasien.kd_penyakit='A15.1' OR diagnosa_pasien.kd_penyakit='A90' OR diagnosa_pasien.kd_penyakit='A91' "
                    + "OR diagnosa_pasien.kd_penyakit='A01.0' OR diagnosa_pasien.kd_penyakit='B54' OR diagnosa_pasien.kd_penyakit='A82.9' "
                    + "OR diagnosa_pasien.kd_penyakit='B24' OR diagnosa_pasien.kd_penyakit='B23.0' OR diagnosa_pasien.kd_penyakit='B22.2' "
                    + "OR diagnosa_pasien.kd_penyakit='Z71.7' OR diagnosa_pasien.kd_penyakit='R75' OR diagnosa_pasien.kd_penyakit='B20.6' "
                    + "OR diagnosa_pasien.kd_penyakit='B20.4' OR diagnosa_pasien.kd_penyakit='B20.7' OR diagnosa_pasien.kd_penyakit='K73.8' "
                    + "OR diagnosa_pasien.kd_penyakit='K73.9' OR diagnosa_pasien.kd_penyakit='O98.4' OR diagnosa_pasien.kd_penyakit='B17.1' "
                    + "OR diagnosa_pasien.kd_penyakit='B17.2' OR diagnosa_pasien.kd_penyakit='B17.9' OR diagnosa_pasien.kd_penyakit='B17.8' "
                    + "OR diagnosa_pasien.kd_penyakit='B18.8' OR diagnosa_pasien.kd_penyakit='B18.9' OR diagnosa_pasien.kd_penyakit='B18.8' "
                    + "OR diagnosa_pasien.kd_penyakit='B18.9' OR diagnosa_pasien.kd_penyakit='B18.2' OR diagnosa_pasien.kd_penyakit='B18.0' "
                    + "OR diagnosa_pasien.kd_penyakit='B05.9' OR diagnosa_pasien.kd_penyakit='B05.8' OR diagnosa_pasien.kd_penyakit='U07.1' "
                    + "OR diagnosa_pasien.kd_penyakit='U07.2' OR diagnosa_pasien.kd_penyakit='J18.9' OR diagnosa_pasien.kd_penyakit='J18.8' "
                    + "OR diagnosa_pasien.kd_penyakit='J17.0' OR diagnosa_pasien.kd_penyakit='J16.8' OR diagnosa_pasien.kd_penyakit='J18.0' "
                    + "OR diagnosa_pasien.kd_penyakit='Z20.3' OR diagnosa_pasien.kd_penyakit='G00.9' OR diagnosa_pasien.kd_penyakit='G03.9' "
                    + "OR diagnosa_pasien.kd_penyakit='A87.9' OR diagnosa_pasien.kd_penyakit='A17.0' OR diagnosa_pasien.kd_penyakit='A30.8' "
                    + "OR diagnosa_pasien.kd_penyakit='A30.9') GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML5.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari7() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,"
                    + "pasien.nm_pasien,concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,"
                    + "(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') FROM diagnosa_pasien "
                    + "INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,"
                    + "pasien.no_ktp,concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,"
                    + "reg_periksa.status_poli,pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? "
                    + "AND (diagnosa_pasien.kd_penyakit='E45' OR diagnosa_pasien.kd_penyakit='O31.2' OR diagnosa_pasien.kd_penyakit='Z30.1' "
                    + "OR diagnosa_pasien.kd_penyakit='O02.1' OR diagnosa_pasien.kd_penyakit='O20.0' OR diagnosa_pasien.kd_penyakit='O03.4' "
                    + "OR diagnosa_pasien.kd_penyakit='O03.9' OR diagnosa_pasien.kd_penyakit='O00.0' OR diagnosa_pasien.kd_penyakit='Z30.4' "
                    + "OR diagnosa_pasien.kd_penyakit='Z30.9' OR diagnosa_pasien.kd_penyakit='Z30.0' OR diagnosa_pasien.kd_penyakit='Z33' "
                    + "OR diagnosa_pasien.kd_penyakit='Z34.0' OR diagnosa_pasien.kd_penyakit='Z34.8' OR diagnosa_pasien.kd_penyakit='Z34.9' "
                    + "OR diagnosa_pasien.kd_penyakit='Z12.4' OR diagnosa_pasien.kd_penyakit LIKE \"%Z35.%\") "
                    + "GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                     l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML6.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari8() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>No Rawat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Jenis Kelamin</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Umur</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal Periksa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status Pulang</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT rp.no_rawat,rp.no_rkm_medis,p.nm_pasien,p.jk,CONCAT(rp.umurdaftar,' ',rp.sttsumur) as umur,DATE_FORMAT(rp.tgl_registrasi,'%d-%m-%Y') as tgl_periksa,rp.status_lanjut,dp.kd_penyakit,IFNULL(ki.stts_pulang,'Ralan') as status\n" +
                "FROM reg_periksa rp \n" +
                "INNER JOIN diagnosa_pasien dp ON dp.no_rawat = rp.no_rawat \n" +
                "inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis \n" +
                "LEFT JOIN kamar_inap ki on ki.no_rawat =rp.no_rawat \n" +
                "WHERE rp.tgl_registrasi BETWEEN ? AND ? AND IFNULL(ki.stts_pulang,'Ralan') <>'Pindah Kamar'\n" +
                "AND dp.kd_penyakit REGEXP '^(J0[0-6,9]|J1[0-8]|J2[0-2])'\n" +
                "GROUP BY rp.no_rkm_medis,dp.kd_penyakit \n" +
                "ORDER by rp.no_rkm_medis");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rawat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("jk")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("umur")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tgl_periksa")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_lanjut")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("kd_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status")+"</td>"+
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 7 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML7.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari9() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tanggal</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>No RM</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>L</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>P</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='20%'>Alamat</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Status</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='9%'>No Telp</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT diagnosa_pasien.no_rawat,DATE_FORMAT(reg_periksa.tgl_registrasi,'%d %M %Y') as tanggal,reg_periksa.no_rkm_medis,"
                    + "pasien.nm_pasien,concat(reg_periksa.umurdaftar,\" \",reg_periksa.sttsumur) as umur,pasien.jk,(SELECT GROUP_CONCAT(DISTINCT penyakit.nm_penyakit SEPARATOR ' + ') "
                    + "FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit WHERE diagnosa_pasien.no_rawat=reg_periksa.no_rawat) as nm_penyakit,pasien.no_ktp,"
                    + "concat(pasien.alamat,\", \",kelurahan.nm_kel,\", \",kecamatan.nm_kec,\", \",kabupaten.nm_kab) as alamat,reg_periksa.status_poli,"
                    + "pasien.no_tlp FROM diagnosa_pasien INNER JOIN penyakit ON penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "
                    + "INNER JOIN reg_periksa ON reg_periksa.no_rawat=diagnosa_pasien.no_rawat INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis "
                    + "INNER JOIN kelurahan ON kelurahan.kd_kel=pasien.kd_kel INNER JOIN kecamatan ON kecamatan.kd_kec=pasien.kd_kec "
                    + "INNER JOIN kabupaten ON kabupaten.kd_kab=pasien.kd_kab WHERE reg_periksa.tgl_registrasi BETWEEN ? AND ? "
                    + "AND diagnosa_pasien.kd_penyakit IN (\n" +
                    "      'I10', 'I15.9', 'I15.1', 'I27.2', 'O10.0', 'O10.4', 'O10.9', \n" +
                    "      'O15.2', 'O15.8', 'I27.0'\n" +
                    "  )"+
                    " OR \n" +
                    "    diagnosa_pasien.kd_penyakit REGEXP '^(J0[0-6,9]|J1[0-8]|J2[0-2])'\n" +
                    "  )\n" 
                    + " and reg_periksa.status_lanjut ='Ranap' "
                    + "GROUP BY reg_periksa.no_rkm_medis order by reg_periksa.tgl_registrasi ASC;");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    l="";
                    p="";
                    if(rs.getString("jk").equals("L")){
                        l=rs.getString("umur");
                    }else if(rs.getString("jk").equals("P")){
                        p=rs.getString("umur");
                    }
                    htmlContent.append(
                        "<tr class='isi'>"+
                            "<td valign='middle' align='center'>"+i+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("tanggal")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_rkm_medis")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                            "<td valign='middle' align='center'>"+l+"</td>"+
                            "<td valign='middle' align='center'>"+p+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                            "<td valign='middle' align='left'>"+rs.getString("alamat")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("status_poli")+"</td>"+
                            "<td valign='middle' align='center'>"+rs.getString("no_tlp")+"</td>"+ 
                        "</tr>"
                    );
                    i++;
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari() 3 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML8.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari() 5 : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());    
    }
    
    private void prosesCari10() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(                             
                "<tr class='isi'>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>No</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tgl Pemeriksaan</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>NIK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='19%'>Nama</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tgl Lahir</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='2%'>JK</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Nama Ibu</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Alamat KTP</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Alamat Domisili</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>No HP</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='5%'>Tgl Diagnosa</td>"+
                    "<td valign='middle' bgcolor='#FFFAFA' align='center' width='10%'>Diagnosa Awal</td>"+
                "</tr>"
            );            
            ps=koneksi.prepareStatement("SELECT rp.tgl_registrasi,p.no_ktp,p.nm_pasien ,p.tgl_lahir, p.jk ,p.nm_ibu,CONCAT(p.alamat,' ',k.nm_kel ,' ',k2.nm_kec ,' ',k3.nm_kab) as alamat,\n" +
                    "CONCAT(p.alamatpj,' ',p.kelurahanpj,' ',p.kecamatanpj,' ',p.kabupatenpj) as alamatpj,p.no_tlp ,IFNULL(MIN(pr.tgl_perawatan),SUBSTRING(pmi.tanggal,1,10)) as tgl_diagnosa,p2.nm_penyakit \n" +
                    "FROM reg_periksa rp \n" +
                    "inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis \n" +
                    "left join diagnosa_pasien dp on dp.no_rawat =rp.no_rawat\n" +
                    "inner join kelurahan k on k.kd_kel =p.kd_kel \n" +
                    "inner join kecamatan k2 on k2.kd_kec =p.kd_kec \n" +
                    "inner join kabupaten k3 on k3.kd_kab =p.kd_kab\n" +
                    "left join pemeriksaan_ralan pr on pr.no_rawat =rp.no_rawat \n" +
                    "left JOIN penilaian_medis_igd pmi on pmi.no_rawat =rp.no_rawat \n" +
                    "left join penyakit p2 on p2.kd_penyakit =dp.kd_penyakit \n" +
                    "WHERE rp.tgl_registrasi BETWEEN ? AND ? AND (dp.kd_penyakit LIKE 'A90%' or dp.kd_penyakit LIKE 'A91%')\n" +
                    "GROUP BY p.no_ktp,MONTH(rp.tgl_registrasi)\n" +
                    "ORDER by rp.tgl_registrasi ");
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                i=1;
                while(rs.next()){
                    htmlContent.append(
                            "<tr class='isi'>"+
                                "<td valign='middle' align='center'>"+i+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tgl_registrasi")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("no_ktp")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_pasien")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tgl_lahir")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("jk")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("nm_ibu")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("alamat")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("alamatpj")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("no_tlp")+"</td>"+
                                "<td valign='middle' align='center'>"+rs.getString("tgl_diagnosa")+"</td>"+
                                "<td valign='middle' align='left'>"+rs.getString("nm_penyakit")+"</td>"+
                            "</tr>"
                        );
                        i++;
                    }
            } catch (Exception e) {
                System.out.println("laporan.DlgLaporanRM.prosesCari10() : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
            LoadHTML9.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgLaporanRM.prosesCari10() : "+e);
        } 
        this.setCursor(Cursor.getDefaultCursor());
    }
}
