/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLhtBiaya.java
 *
 * Created on 12 Jul 10, 16:21:34
 */

package laporan;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author perpustakaan
 */
public final class DlgRl35 extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i=0,lakidalam=0,perempuandalam=0,lainLakidalam=0,lainPerempuandalam=0,anakLakidalam=0,anakPerempuandalam=0,anakLakiNdalam=0,
            anakPerempuanNdalam=0,obgynhamildalam=0,obgyndalam=0,ttllakidalam=0,ttlperempuandalam=0,ttllainLakidalam=0,ttllainPerempuandalam=0,
            ttlanakLakidalam=0,ttlanakPerempuandalam=0,lakiluar=0,perempuanluar=0,lainLakiluar=0,lainPerempuanluar=0,anakLakiluar=0,
            anakPerempuanluar=0,anakLakiNluar=0,anakPerempuanNluar=0,obgynhamilluar=0,obgynluar=0,ttllakiluar=0,ttlperempuanluar=0,
            ttllainLakiluar=0,ttllainPerempuanluar=0,ttlanakLakiluar=0,ttlanakPerempuanluar=0,ttl=0,ttl2=0,ttl3=0,ttl4=0,ttl5=0,ttl6=0,ttl7=0,ttl8=0;   
    /** Creates new form DlgLhtBiaya
     * @param parent
     * @param modal */
    public DlgRl35(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(8,1);
        setSize(885,674);

        Object[] rowRwJlDr={"Jenis Pelayanan","Jumlah Laki-Laki Dalam Kota","Jumlah Perempuan Dalam Kota","Jumlah Laki-Laki Luar Kota",
            "Jumlah Perempuan Luar Kota","Total Kunjungan"};
        tabMode=new DefaultTableModel(null,rowRwJlDr){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbBangsal.setModel(tabMode);
        //tbBangsal.setDefaultRenderer(Object.class, new WarnaTable(jPanel2.getBackground(),tbBangsal.getBackground()));
        tbBangsal.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbBangsal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 6; i++) {
            TableColumn column = tbBangsal.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(200);
            }else if(i==1){
                column.setPreferredWidth(200);
            }else if(i==2){
                column.setPreferredWidth(200);
            }else if(i==3){
                column.setPreferredWidth(200);
            }else if(i==4){
                column.setPreferredWidth(200);
            }else if(i==5){
                column.setPreferredWidth(150);
            }
        }
        tbBangsal.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
                   

        
        try {
            ps=koneksi.prepareStatement(
                    "select poliklinik.kd_poli,poliklinik.nm_poli,SUBSTRING(poliklinik.nm_poli, LOCATE(' ', poliklinik.nm_poli) + 1) AS kata_kedua from poliklinik " +
                    "where poliklinik.nm_poli like ? and poliklinik.nm_poli not like '%Anestesi%' and "+
                    "poliklinik.nm_poli not like '%Poliklinik KB%' and poliklinik.nm_poli not like '%Kendedes%' and "+
                    "poliklinik.nm_poli not like '%Orthopedi%' and poliklinik.nm_poli not like '%Persiapan%' and poliklinik.nm_poli not like '%Urologi%' and "+
                    "poliklinik.nm_poli not like '%Anak%' and poliklinik.nm_poli not like '%Obgyn%' and poliklinik.nm_poli not like '%Bayi Baru Lahir%' and "+
                    "poliklinik.nm_poli not like '%Farmasi%' and poliklinik.nm_poli not like '%Homecare%' and poliklinik.nm_poli not like '%Laboratorium%' and "+
                    "poliklinik.nm_poli not like '%Telemedicine%' and poliklinik.nm_poli not like '%Dialisis%' and poliklinik.nm_poli not like '%Radiologi%' "+
                    "and poliklinik.status='1' order by poliklinik.nm_poli");
        } catch (Exception e) {
            System.out.println(e);
        }
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbBangsal = new widget.Table();
        panelGlass5 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 3.5 Kunjungan ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbBangsal.setName("tbBangsal"); // NOI18N
        Scroll.setViewportView(tbBangsal);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass5.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(25, 23));
        panelGlass5.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl2);

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass5.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(155, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass5.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnAll);

        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass5.add(jLabel7);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            //TCari.requestFocus();
        }else if(tabMode.getRowCount()!=0){
            
            Map<String, Object> param = new HashMap<>();         
            param.put("namars",akses.getnamars());
            param.put("alamatrs",akses.getalamatrs());
            param.put("kotars",akses.getkabupatenrs());
            param.put("propinsirs",akses.getpropinsirs());
            param.put("kontakrs",akses.getkontakrs());
            param.put("emailrs",akses.getemailrs());   
            param.put("periode",Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem());  
            param.put("tanggal",Tgl2.getDate());  
            param.put("logo",Sequel.cariGambar("select setting.logo from setting"));  
            Sequel.queryu("delete from temporary where temp37='"+akses.getalamatip()+"'");
            for(int r=0;r<tabMode.getRowCount();r++){ 
                if(!tbBangsal.getValueAt(r,0).toString().contains(">>")){
                    Sequel.menyimpan("temporary","'"+r+"','"+
                                    tabMode.getValueAt(r,0).toString()+"','"+
                                    tabMode.getValueAt(r,1).toString()+"','"+
                                    tabMode.getValueAt(r,2).toString()+"','"+
                                    tabMode.getValueAt(r,3).toString()+"','"+
                                    tabMode.getValueAt(r,4).toString()+"','"+
                                    tabMode.getValueAt(r,5).toString()+"','"+
                                    tabMode.getValueAt(r,6).toString()+"','"+
                                    tabMode.getValueAt(r,7).toString()+"','"+
                                    tabMode.getValueAt(r,8).toString()+"','','','','','','','','','','','','','','','','','','','','','','','','','','','','"+akses.getalamatip()+"'","Rekap Nota Pembayaran");
                }                    
            }
               
            Valid.MyReportqry("rptRl35.jasper","report","::[ Formulir RL 3.2 ]::","select * from temporary where temporary.temp37='"+akses.getalamatip()+"' order by temporary.no",param);
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            //Valid.pindah(evt, BtnHapus, BtnAll);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnKeluar,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
       tampil();
}//GEN-LAST:event_BtnCariActionPerformed

private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
            tampil();
            this.setCursor(Cursor.getDefaultCursor());
        }else{
            Valid.pindah(evt, TCari, BtnPrint);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
           TCari.setText("");
           tampil();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampil();

    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRl35 dialog = new DlgRl35(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label label11;
    private widget.Label label18;
    private widget.panelisi panelGlass5;
    private widget.Table tbBangsal;
    // End of variables declaration//GEN-END:variables

    public void tampil(){        
        try{   
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
            Valid.tabelKosong(tabMode);   
            ps.setString(1,"%"+TCari.getText().trim()+"%");
            rs=ps.executeQuery();
            i=1;
            lakidalam=0;
            perempuandalam=0;
            lainLakidalam=0;
            lainPerempuandalam=0;
            anakLakiNdalam=0;
            anakPerempuanNdalam=0;
            anakLakidalam=0;
            anakPerempuandalam=0;
            obgynhamildalam=0;
            obgyndalam=0;
            lakiluar=0;
            perempuanluar=0;
            lainLakiluar=0;
            lainPerempuanluar=0;
            anakLakiNluar=0;
            anakPerempuanNluar=0;
            anakLakiluar=0;
            anakPerempuanluar=0;
            obgynhamilluar=0;
            obgynluar=0;
//            ttllaki=0;
//            ttlperempuan=0;
//            ttllainLaki=0;
//            ttllainPerempuan=0;
//            ttlanakLaki=0;
//            ttlanakPerempuan=0;
            ttl=0;
            ttl2=0;
            ttl3=0;
            ttl4=0;
            ttl5=0;
            ttl6=0;
            ttl7=0;
            ttl8=0;
            while(rs.next()){
                lakidalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab "
                        + " where p.jk='L' and rp.kd_poli='"+rs.getString("kd_poli")+"' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                perempuandalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='"+rs.getString("kd_poli")+"' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                lainLakidalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and (rp.kd_poli='U0007' or rp.kd_poli='U0010' or rp.kd_poli='U0035') and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                lainPerempuandalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and (rp.kd_poli='U0007' or rp.kd_poli='U0010' or rp.kd_poli='U0035') and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                anakLakidalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)>28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                anakPerempuandalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)>28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                anakLakiNdalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)<28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                anakPerempuanNdalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)<28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                obgyndalam=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0001' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                obgynhamildalam=Sequel.cariInteger("SELECT COUNT(DISTINCT rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab left join diagnosa_pasien dp on dp.no_rawat =rp.no_rawat"
                        + " where p.jk='P' and rp.kd_poli='U0001' AND (dp.kd_penyakit like '%Z34%' or dp.kd_penyakit like '%Z35%' or dp.kd_penyakit like '%O00%' " +
                        "or dp.kd_penyakit like '%O01%' or dp.kd_penyakit like '%O21%' or dp.kd_penyakit like '%O24%' or dp.kd_penyakit like '%O98.7%') " +
                        "and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab LIKE '%Badung'");
                
                lakiluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab "
                        + " where p.jk='L' and rp.kd_poli='"+rs.getString("kd_poli")+"' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                perempuanluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='"+rs.getString("kd_poli")+"' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                lainLakiluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and (rp.kd_poli='U0007' or rp.kd_poli='U0010' or rp.kd_poli='U0035') and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                lainPerempuanluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and (rp.kd_poli='U0007' or rp.kd_poli='U0010' or rp.kd_poli='U0035') and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                anakLakiluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)>28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                anakPerempuanluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)>28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                anakLakiNluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='L' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)<28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                anakPerempuanNluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0003' and DATEDIFF(CURDATE(), p.tgl_lahir)<28 and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                obgynluar=Sequel.cariInteger("SELECT COUNT(rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab"
                        + " where p.jk='P' and rp.kd_poli='U0001' and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                obgynhamilluar=Sequel.cariInteger("SELECT COUNT(DISTINCT rp.no_rawat) FROM reg_periksa rp inner join pasien p on p.no_rkm_medis =rp.no_rkm_medis inner join kabupaten k on k.kd_kab =p.kd_kab left join diagnosa_pasien dp on dp.no_rawat =rp.no_rawat"
                        + " where p.jk='P' and rp.kd_poli='U0001' AND (dp.kd_penyakit like '%Z34%' or dp.kd_penyakit like '%Z35%' or dp.kd_penyakit like '%O00%' " +
                        "or dp.kd_penyakit like '%O01%' or dp.kd_penyakit like '%O21%' or dp.kd_penyakit like '%O24%' or dp.kd_penyakit like '%O98.7%') " +
                        "and rp.tgl_registrasi between '"+Valid.SetTgl(Tgl1.getSelectedItem()+"")+"' and '"+Valid.SetTgl(Tgl2.getSelectedItem()+"")+"' and k.nm_kab NOT LIKE '%Badung'");
                
                ttl=lakidalam+perempuandalam+lakiluar+perempuanluar;
                ttl2=lainLakidalam+lainPerempuandalam+lainLakiluar+lainPerempuanluar;
                ttl3=anakLakidalam+anakPerempuandalam+anakLakiluar+anakPerempuanluar;
                ttl4=anakLakiNdalam+anakPerempuanNdalam+anakLakiNluar+anakPerempuanNluar;
                ttl5=obgyndalam-obgynhamildalam;
                ttl6=obgynhamildalam+obgynhamilluar;
                ttl7=obgynluar-obgynhamilluar;
                ttl8=ttl5+ttl7;
                tabMode.addRow(new Object[]{
                    rs.getString("kata_kedua"),lakidalam,perempuandalam,lakiluar,perempuanluar,ttl
                });
                i++;
            }
            if(i>1){
                
                tabMode.addRow(new Object[]{
                    "Lain-Lain",lainLakidalam,lainPerempuandalam,lainLakiluar,lainPerempuanluar,ttl2
                });
                tabMode.addRow(new Object[]{
                    "Anak (Neonatal)",anakLakiNdalam,anakPerempuanNdalam,anakLakiNluar,anakPerempuanNluar,ttl4
                });
                tabMode.addRow(new Object[]{
                    "Anak",anakLakidalam,anakPerempuandalam,anakLakiluar,anakPerempuanluar,ttl3
                });
                tabMode.addRow(new Object[]{
                    "Obgyn (Ibu Hamil)","0",obgynhamildalam,"0",obgynhamilluar,ttl6
                });
                tabMode.addRow(new Object[]{
                    "Obgyn","0",ttl5,"0",ttl7,ttl8
                });
            }
            this.setCursor(Cursor.getDefaultCursor());
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
    }

}
