package laporan;
import ipsrs.*;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import simrskhanza.DlgCariCaraBayar;

public class DlgRekapRegistrasi extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private Connection koneksi=koneksiDB.condb();
    private DlgCariCaraBayar penjab=new DlgCariCaraBayar(null,false);
    private PreparedStatement ps,ps2,ps3;
    private ResultSet rs,rs2,rs3;
    
    private int i=0,z=0,x=1;
    private boolean[] pilihan;
    private String[] kodebarang,namabarang,satuan,jenis,jumlah,kodesat,ruangan,keterangan;
    private double total=0,jml=0,kur15=0,leb15=0;
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgRekapRegistrasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Object[] row={"No","No Rawat","Tujuan","Tgl Antrian","Jam Mulai","Jam Akhir","Selisih"};
        tabMode=new DefaultTableModel(null,row){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){
                boolean a = false;
                if (colIndex==0) {
                    a=true;
                }
                return a;
             }
             Class[] types = new Class[] {
                java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,
                java.lang.Object.class,java.lang.Object.class,java.lang.Object.class,
                java.lang.Object.class
             };
             /*Class[] types = new Class[] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
             };*/
             @Override
             public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
             }
        };
        tbDokter.setModel(tabMode);

        tbDokter.setPreferredScrollableViewportSize(new Dimension(800,800));
        tbDokter.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0;i < 7; i++) {
            TableColumn column = tbDokter.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(25);
            }else if(i==1){
                column.setPreferredWidth(125);
            }else if(i==2){
                column.setPreferredWidth(200);
            }else if(i==3){
                column.setPreferredWidth(75);
            }else if(i==4){
                column.setPreferredWidth(75);
            }else if(i==5){
                column.setPreferredWidth(75);
            }else if(i==6){
                column.setPreferredWidth(100);
            }
        }
        tbDokter.setDefaultRenderer(Object.class, new WarnaTable());   
        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        prosesCari();
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        prosesCari();
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        prosesCari();
                    }
                }
            });
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup2 = new javax.swing.JPopupMenu();
        Alasan = new javax.swing.JMenuItem();
        Alasan1 = new javax.swing.JMenuItem();
        Alasan2 = new javax.swing.JMenuItem();
        Alasan3 = new javax.swing.JMenuItem();
        Alasan4 = new javax.swing.JMenuItem();
        Alasan5 = new javax.swing.JMenuItem();
        Alasan6 = new javax.swing.JMenuItem();
        Alasan7 = new javax.swing.JMenuItem();
        Alasan8 = new javax.swing.JMenuItem();
        Alasan9 = new javax.swing.JMenuItem();
        Alasan10 = new javax.swing.JMenuItem();
        Alasan11 = new javax.swing.JMenuItem();
        Alasan12 = new javax.swing.JMenuItem();
        Alasan13 = new javax.swing.JMenuItem();
        Alasan14 = new javax.swing.JMenuItem();
        Alasan15 = new javax.swing.JMenuItem();
        Alasan16 = new javax.swing.JMenuItem();
        Alasan17 = new javax.swing.JMenuItem();
        Alasan18 = new javax.swing.JMenuItem();
        internalFrame1 = new widget.InternalFrame();
        scrollPane1 = new widget.ScrollPane();
        tbDokter = new widget.Table();
        panelisi4 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        label12 = new widget.Label();
        Antrean = new javax.swing.JComboBox<>();
        panelisi1 = new widget.panelisi();
        label9 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        label10 = new widget.Label();
        BtnKeluar = new widget.Button();

        Popup2.setName("Popup2"); // NOI18N

        Alasan.setBackground(new java.awt.Color(255, 255, 254));
        Alasan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan.setForeground(new java.awt.Color(50, 50, 50));
        Alasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan.setText("Sesuai Target");
        Alasan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan.setName("Alasan"); // NOI18N
        Alasan.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlasanActionPerformed(evt);
            }
        });
        Popup2.add(Alasan);

        Alasan1.setBackground(new java.awt.Color(255, 255, 254));
        Alasan1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan1.setForeground(new java.awt.Color(50, 50, 50));
        Alasan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan1.setText("Menunggu Ruangan Siap");
        Alasan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan1.setName("Alasan1"); // NOI18N
        Alasan1.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan1ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan1);

        Alasan2.setBackground(new java.awt.Color(255, 255, 254));
        Alasan2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan2.setForeground(new java.awt.Color(50, 50, 50));
        Alasan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan2.setText("Pasien Lama Memutuskan Setuju Ranap");
        Alasan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan2.setName("Alasan2"); // NOI18N
        Alasan2.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan2ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan2);

        Alasan3.setBackground(new java.awt.Color(255, 255, 254));
        Alasan3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan3.setForeground(new java.awt.Color(50, 50, 50));
        Alasan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan3.setText("Pasien Lama Memutuskan Setuju Tindakan Medis");
        Alasan3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan3.setName("Alasan3"); // NOI18N
        Alasan3.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan3ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan3);

        Alasan4.setBackground(new java.awt.Color(255, 255, 254));
        Alasan4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan4.setForeground(new java.awt.Color(50, 50, 50));
        Alasan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan4.setText("Tidak Ada Penanggung Jawab Pasien");
        Alasan4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan4.setName("Alasan4"); // NOI18N
        Alasan4.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan4ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan4);

        Alasan5.setBackground(new java.awt.Color(255, 255, 254));
        Alasan5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan5.setForeground(new java.awt.Color(50, 50, 50));
        Alasan5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan5.setText("Menunggu Hasil Lab");
        Alasan5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan5.setName("Alasan5"); // NOI18N
        Alasan5.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan5ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan5);

        Alasan6.setBackground(new java.awt.Color(255, 255, 254));
        Alasan6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan6.setForeground(new java.awt.Color(50, 50, 50));
        Alasan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan6.setText("Menunggu Hasil Rontgen");
        Alasan6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan6.setName("Alasan6"); // NOI18N
        Alasan6.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan6ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan6);

        Alasan7.setBackground(new java.awt.Color(255, 255, 254));
        Alasan7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan7.setForeground(new java.awt.Color(50, 50, 50));
        Alasan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan7.setText("Mencari Rujukan");
        Alasan7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan7.setName("Alasan7"); // NOI18N
        Alasan7.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan7ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan7);

        Alasan8.setBackground(new java.awt.Color(255, 255, 254));
        Alasan8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan8.setForeground(new java.awt.Color(50, 50, 50));
        Alasan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan8.setText("Menunggu Obat");
        Alasan8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan8.setName("Alasan8"); // NOI18N
        Alasan8.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan8ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan8);

        Alasan9.setBackground(new java.awt.Color(255, 255, 254));
        Alasan9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan9.setForeground(new java.awt.Color(50, 50, 50));
        Alasan9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan9.setText("Menunggu Pendaftaran");
        Alasan9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan9.setName("Alasan9"); // NOI18N
        Alasan9.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan9ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan9);

        Alasan10.setBackground(new java.awt.Color(255, 255, 254));
        Alasan10.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan10.setForeground(new java.awt.Color(50, 50, 50));
        Alasan10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan10.setText("Butuh Perpanjangan Observasi");
        Alasan10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan10.setName("Alasan10"); // NOI18N
        Alasan10.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan10ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan10);

        Alasan11.setBackground(new java.awt.Color(255, 255, 254));
        Alasan11.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan11.setForeground(new java.awt.Color(50, 50, 50));
        Alasan11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan11.setText("Menunggu Keputusan Keluarga");
        Alasan11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan11.setName("Alasan11"); // NOI18N
        Alasan11.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan11ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan11);

        Alasan12.setBackground(new java.awt.Color(255, 255, 254));
        Alasan12.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan12.setForeground(new java.awt.Color(50, 50, 50));
        Alasan12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan12.setText("Menunggu USG Abdomen");
        Alasan12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan12.setName("Alasan12"); // NOI18N
        Alasan12.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan12ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan12);

        Alasan13.setBackground(new java.awt.Color(255, 255, 254));
        Alasan13.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan13.setForeground(new java.awt.Color(50, 50, 50));
        Alasan13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan13.setText("Menunggu Dilakukan Echo di Poli");
        Alasan13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan13.setName("Alasan13"); // NOI18N
        Alasan13.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan13ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan13);

        Alasan14.setBackground(new java.awt.Color(255, 255, 254));
        Alasan14.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan14.setForeground(new java.awt.Color(50, 50, 50));
        Alasan14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan14.setText("Menunggu Visite DPJP");
        Alasan14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan14.setName("Alasan14"); // NOI18N
        Alasan14.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan14ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan14);

        Alasan15.setBackground(new java.awt.Color(255, 255, 254));
        Alasan15.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan15.setForeground(new java.awt.Color(50, 50, 50));
        Alasan15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan15.setText("Menunggu Advice DPJP");
        Alasan15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan15.setName("Alasan15"); // NOI18N
        Alasan15.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan15ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan15);

        Alasan16.setBackground(new java.awt.Color(255, 255, 254));
        Alasan16.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan16.setForeground(new java.awt.Color(50, 50, 50));
        Alasan16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan16.setText("Observasi PK I Fase Laten");
        Alasan16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan16.setName("Alasan16"); // NOI18N
        Alasan16.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan16ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan16);

        Alasan17.setBackground(new java.awt.Color(255, 255, 254));
        Alasan17.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan17.setForeground(new java.awt.Color(50, 50, 50));
        Alasan17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan17.setText("Observasi di VK");
        Alasan17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan17.setName("Alasan17"); // NOI18N
        Alasan17.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan17ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan17);

        Alasan18.setBackground(new java.awt.Color(255, 255, 254));
        Alasan18.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Alasan18.setForeground(new java.awt.Color(50, 50, 50));
        Alasan18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/category.png"))); // NOI18N
        Alasan18.setText("Full Bed IGD");
        Alasan18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Alasan18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Alasan18.setName("Alasan18"); // NOI18N
        Alasan18.setPreferredSize(new java.awt.Dimension(225, 25));
        Alasan18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alasan18ActionPerformed(evt);
            }
        });
        Popup2.add(Alasan18);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Rekap Registrasi ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        scrollPane1.setName("scrollPane1"); // NOI18N
        scrollPane1.setOpaque(true);

        tbDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbDokter.setName("tbDokter"); // NOI18N
        scrollPane1.setViewportView(tbDokter);

        internalFrame1.add(scrollPane1, java.awt.BorderLayout.CENTER);

        panelisi4.setName("panelisi4"); // NOI18N
        panelisi4.setPreferredSize(new java.awt.Dimension(100, 44));
        panelisi4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi4.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        Tgl1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl1KeyPressed(evt);
            }
        });
        panelisi4.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi4.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        Tgl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tgl2KeyPressed(evt);
            }
        });
        panelisi4.add(Tgl2);

        label12.setText("Jenis :");
        label12.setName("label12"); // NOI18N
        label12.setPreferredSize(new java.awt.Dimension(50, 23));
        panelisi4.add(label12);

        Antrean.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IGD", "Poliklinik" }));
        Antrean.setName("Antrean"); // NOI18N
        panelisi4.add(Antrean);

        internalFrame1.add(panelisi4, java.awt.BorderLayout.PAGE_START);

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label9.setText("Key Word :");
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(68, 23));
        panelisi1.add(label9);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(200, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelisi1.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('1');
        BtnCari.setToolTipText("Alt+1");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelisi1.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('2');
        BtnAll.setToolTipText("Alt+2");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelisi1.add(BtnAll);

        label10.setName("label10"); // NOI18N
        label10.setPreferredSize(new java.awt.Dimension(25, 23));
        panelisi1.add(label10);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleName("::[Laporan Jenis Pembayaran Ranap Marketing ]::");
        internalFrame1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void Tgl1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl1KeyPressed
        Valid.pindah(evt, BtnKeluar,Tgl2);
    }//GEN-LAST:event_Tgl1KeyPressed

    private void Tgl2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tgl2KeyPressed
        
    }//GEN-LAST:event_Tgl2KeyPressed

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        prosesCari();
    }//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, TCari, BtnAll);
        }
    }//GEN-LAST:event_BtnCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        prosesCari();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            Valid.pindah(evt, BtnCari, TCari);
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prosesCari();
    }//GEN-LAST:event_formWindowOpened

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCariKeyPressed

    private void AlasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlasanActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Sesuai Target'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Sesuai Target",tbDokter.getSelectedRow(),22);
            }
        }
    }//GEN-LAST:event_AlasanActionPerformed

    private void Alasan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan1ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Ruangan Siap'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Ruangan Siap",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan1ActionPerformed

    private void Alasan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan2ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Pasien Lama Memutuskan Setuju Ranap'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Pasien Lama Memutuskan Setuju Ranap",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan2ActionPerformed

    private void Alasan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan3ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Pasien Lama Memutuskan Setuju Tindakan Medis'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Pasien Lama Memutuskan Setuju Tindakan Medis",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan3ActionPerformed

    private void Alasan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan4ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Tidak Ada Penanggung Jawab Pasien'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Tidak Ada Penanggung Jawab Pasien",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan4ActionPerformed

    private void Alasan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan5ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Hasil Lab'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Hasil Lab",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan5ActionPerformed

    private void Alasan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan6ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Hasil Rontgen'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Hasil Rontgen",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan6ActionPerformed

    private void Alasan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan7ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Mencari Rujukan'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Mencari Rujukan",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan7ActionPerformed

    private void Alasan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan8ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Obat'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Obat",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan8ActionPerformed

    private void Alasan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan9ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Pendaftaran'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Pendaftaran",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan9ActionPerformed

    private void Alasan10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan10ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Butuh Perpanjangan Observasi'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Butuh Perpanjangan Observasi",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan10ActionPerformed

    private void Alasan11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan11ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Keputusan Keluarga'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Keputusan Keluarga",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan11ActionPerformed

    private void Alasan12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan12ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu USG Abdomen'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu USG Abdomen",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan12ActionPerformed

    private void Alasan13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan13ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Dilakukan Echo di Poli'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Dilakukan Echo di Poli",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan13ActionPerformed

    private void Alasan14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan14ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Visite DPJP'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Visite DPJP",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan14ActionPerformed

    private void Alasan15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan15ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Menunggu Advice DPJP'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Menunggu Advice DPJP",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan15ActionPerformed

    private void Alasan16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan16ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Observasi PK I Fase Laten'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Observasi PK I Fase Laten",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan16ActionPerformed

    private void Alasan17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan17ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Observasi di VK'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Observasi di VK",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan17ActionPerformed

    private void Alasan18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alasan18ActionPerformed
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, pilih data terlebih dahulu...!!!!");
        }else{
            if(tbDokter.getSelectedRow()!= -1){
                Sequel.mengedit("pulang_igd","no_rawat=?","alasan='Full Bed IGD'",1,new String[]{tbDokter.getValueAt(tbDokter.getSelectedRow(),21).toString()});
                tabMode.setValueAt("Full Bed IGD",tbDokter.getSelectedRow(),22);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_Alasan18ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRekapRegistrasi dialog = new DlgRekapRegistrasi(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alasan;
    private javax.swing.JMenuItem Alasan1;
    private javax.swing.JMenuItem Alasan10;
    private javax.swing.JMenuItem Alasan11;
    private javax.swing.JMenuItem Alasan12;
    private javax.swing.JMenuItem Alasan13;
    private javax.swing.JMenuItem Alasan14;
    private javax.swing.JMenuItem Alasan15;
    private javax.swing.JMenuItem Alasan16;
    private javax.swing.JMenuItem Alasan17;
    private javax.swing.JMenuItem Alasan18;
    private javax.swing.JMenuItem Alasan2;
    private javax.swing.JMenuItem Alasan3;
    private javax.swing.JMenuItem Alasan4;
    private javax.swing.JMenuItem Alasan5;
    private javax.swing.JMenuItem Alasan6;
    private javax.swing.JMenuItem Alasan7;
    private javax.swing.JMenuItem Alasan8;
    private javax.swing.JMenuItem Alasan9;
    private javax.swing.JComboBox<String> Antrean;
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private javax.swing.JPopupMenu Popup2;
    private widget.TextBox TCari;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.InternalFrame internalFrame1;
    private widget.Label label10;
    private widget.Label label11;
    private widget.Label label12;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    private widget.panelisi panelisi4;
    private widget.ScrollPane scrollPane1;
    private widget.Table tbDokter;
    // End of variables declaration//GEN-END:variables

    private void prosesCari() {
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
            z=0;
            for(i=0;i<tbDokter.getRowCount();i++){
                if(!tbDokter.getValueAt(i,0).toString().equals("")){
                    z++;
                }
            } 

            pilihan=null;
            pilihan=new boolean[z]; 
            jumlah=null;
            jumlah=new String[z];
            
            namabarang=null;
            namabarang=new String[z];
            

            z=0;        
            for(i=0;i<tbDokter.getRowCount();i++){
                if(tbDokter.getValueAt(i,0).toString().equals("true")){
                    pilihan[z]=Boolean.parseBoolean(tbDokter.getValueAt(i,0).toString());                
                    
                    namabarang[z]=tbDokter.getValueAt(i,1).toString();
                    
                    jumlah[z]=tbDokter.getValueAt(i,2).toString();
                    
                    z++;
                }
            }
            
            Valid.tabelKosong(tabMode);
            for(i=0;i<z;i++){
                tabMode.addRow(new Object[] {
                    pilihan[i],namabarang[i],jumlah[i]
                });
            }
            
            ps=koneksi.prepareStatement(
                "SELECT rp.no_rawat,DATE_FORMAT(rp.tgl_registrasi,'%d-%m-%Y') as tanggal,rp.jam_reg,rs.jam_selesai,\n" +
                "if(rs.jam_selesai='00:00:00','',if(rs.jam_selesai<rp.jam_reg,'',TIMESTAMPDIFF(minute, concat(rp.tgl_registrasi,' ',rp.jam_reg),concat(rs.tgl_selesai,' ',rs.jam_selesai)))) as durasi,p.nm_poli\n" +
                "FROM reg_periksa rp \n" +
                "inner join poliklinik p on p.kd_poli=rp.kd_poli \n" +
                "left join regis_selesai rs on rs.no_rawat=rp.no_rawat \n" +
                "WHERE rp.tgl_registrasi BETWEEN ? and ? and p.nm_poli like ? ");
                                        
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                ps.setString(3,"%"+Antrean.getSelectedItem().toString()+"%");
                x=1;
                total=0;
                kur15=0;
                leb15=0;
                rs=ps.executeQuery();
                while(rs.next()){
                    tabMode.addRow(new Object[]{
                        x++,rs.getString(1),rs.getString(6),rs.getString(2),rs.getString(3),rs.getString(4),
                        rs.getInt(5)+" Menit"
                    });
                    total=total+rs.getInt(5);
                    if(rs.getInt(5)<=15){
                        kur15=kur15+1;
                    }
                    if(rs.getInt(5)>15){
                        leb15=leb15+1;
                    }
                }
                x=x-1;
                tabMode.addRow(new Object[]{"","","","","","",""});
                tabMode.addRow(new Object[]{"","","","","","<15 Menit",": "+kur15});
                tabMode.addRow(new Object[]{"","","","","",">15 Menit",": "+leb15});
                tabMode.addRow(new Object[]{"","","","","","Rata-rata",": "+Valid.SetAngka4(total/x)+" Menit"});
            } catch (Exception e) {
                System.out.println("Note : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }
                                     
            this.setCursor(Cursor.getDefaultCursor());              
        }   catch (Exception e) {
                System.out.println(e);
        }               
    }
}
